INSERT INTO ADDRESS("ADDRESS_ID", "FIRST_LINE", "CITY", "STATE") VALUES (1, '100 East Davie Street', 'Raleigh', 'NC')
INSERT INTO ADDRESS("ADDRESS_ID", "FIRST_LINE", "CITY", "STATE") VALUES (2, '314 Littleton Road', 'Westford', 'MA')
INSERT INTO ADDRESS("ADDRESS_ID", "FIRST_LINE", "CITY", "STATE") VALUES (3, '600 My Street', 'Raleigh', 'NC')
INSERT INTO ADDRESS("ADDRESS_ID", "FIRST_LINE", "CITY", "STATE") VALUES (4, '255 My Crescent', 'Westford', 'MA')

INSERT INTO EMPLOYEE("EMPLOYEE_ID", "FIRST_NAME", "LAST_NAME", "SOCIAL_SECURITY_ID", "SALARY", "HOME_PHONE_NUMBER", "HOME_ADDRESS_ID", "WORK_PHONE_NUMBER", "WORK_ADDRESS_ID") VALUES (1, 'Steve', 'Bishop', '123-45-6789', 45678.00, '123-456-7890', 3, null, 1)
INSERT INTO EMPLOYEE("EMPLOYEE_ID", "FIRST_NAME", "LAST_NAME", "SOCIAL_SECURITY_ID", "SALARY", "HOME_PHONE_NUMBER", "HOME_ADDRESS_ID", "WORK_PHONE_NUMBER", "WORK_ADDRESS_ID") VALUES (2, 'Martin', 'Smith', '987-65-4321', 56740.21, '987-654-3210', 4, null, 2)
