export const LOADING = 'LOADING';
export const NOTIFY_ERROR = 'NOTIFY_ERROR';
export const NOTIFY_SUCCESS = 'NOTIFY_SUCCESS';
export const NOTIFY_RESET = 'NOTIFY_RESET';

export const GET_ADDRESSES_SUCCESS = 'GET_ADDRESSES_SUCCESS';

export const CREATE_ADDRESS = 'CREATE_ADDRESS';
export const CREATE_ADDRESS_SUCCESS = 'CREATE_ADDRESS_SUCCESS';
export const RESET_NEW_ADDRESS = 'RESET_NEW_ADDRESS';

export const GET_ADDRESS = 'GET_ADDRESS';
export const GET_ADDRESS_SUCCESS = 'GET_ADDRESS_SUCCESS';
export const RESET_ACTIVE_ADDRESS = 'RESET_ACTIVE_ADDRESS';

export const UPDATE_ADDRESS = 'UPDATE_ADDRESS';
export const UPDATE_ADDRESS_SUCCESS = 'UPDATE_ADDRESS_SUCCESS';

export const DELETE_ADDRESS_SUCCESS = 'DELETE_ADDRESS_SUCCESS';
