INSERT INTO ADDRESS("ADDRESS_ID", "FIRST_LINE", "CITY", "STATE") VALUES (1, '100 East Davie Street', 'Raleigh', 'NC')
INSERT INTO ADDRESS("ADDRESS_ID", "FIRST_LINE", "CITY", "STATE") VALUES (2, '314 Littleton Road', 'Westford', 'MA')
INSERT INTO ADDRESS("ADDRESS_ID", "FIRST_LINE", "CITY", "STATE") VALUES (3, '600 My Street', 'Raleigh', 'NC')
INSERT INTO ADDRESS("ADDRESS_ID", "FIRST_LINE", "CITY", "STATE") VALUES (4, '255 My Crescent', 'Westford', 'MA')